#### Aquí encontrarás todo lo que necesitas saber: https://www.kaggle.com/t/ab8726f0cfc84544abbae69a6be88071

## Librerias

In [145]:
import pandas as pd

import urllib.request
from PIL import Image

## Data

In [146]:
### Para que funcione necesitas bajarte los archivos de datos de Kaggle 
train = pd.read_csv("data/train.csv")

## Data exploration

In [147]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   laptop_ID         912 non-null    int64  
 1   Company           912 non-null    object 
 2   Product           912 non-null    object 
 3   TypeName          912 non-null    object 
 4   Inches            912 non-null    float64
 5   ScreenResolution  912 non-null    object 
 6   Cpu               912 non-null    object 
 7   Ram               912 non-null    object 
 8   Memory            912 non-null    object 
 9   Gpu               912 non-null    object 
 10  OpSys             912 non-null    object 
 11  Weight            912 non-null    object 
 12  Price_euros       912 non-null    float64
dtypes: float64(2), int64(1), object(10)
memory usage: 92.8+ KB


In [148]:
train.head()

laptop_ID Company            Product   TypeName  Inches  \
0       1104    Acer     Aspire ES1-523   Notebook    15.6   
1        114    Dell             XPS 13  Ultrabook    13.3   
2        172    Acer    Aspire A517-51G   Notebook    17.3   
3        918      HP      Elitebook 820    Netbook    12.5   
4        447  Lenovo  IdeaPad 320-15AST   Notebook    17.3   

                   ScreenResolution                         Cpu  Ram  \
0                          1366x768   AMD A8-Series 7410 2.2GHz  4GB   
1  Quad HD+ / Touchscreen 3200x1800  Intel Core i7 7560U 2.4GHz  8GB   
2       IPS Panel Full HD 1920x1080  Intel Core i5 8250U 1.6GHz  8GB   
3                 Full HD 1920x1080  Intel Core i7 7500U 2.7GHz  8GB   
4                          1600x900   AMD A6-Series 9220 2.5GHz  8GB   

      Memory                           Gpu       OpSys  Weight  Price_euros  
0  500GB HDD                 AMD Radeon R5  Windows 10   2.4kg        387.0  
1  256GB SSD  Intel Iris Plus Graphics 640  Windows 10  1.23kg       1379.0  
2  256GB SSD          Nvidia GeForce MX150  Windows 10     3kg        854.0  
3  512GB SSD         Intel HD Graphics 620  Windows 10  1.26kg       1483.0  
4    1TB HDD                 AMD Radeon R4  Windows 10   2.8kg        519.0

## Data processing

In [149]:
#En la columna "OpSys", convertimos los sistemas en números. Creamos diccionario
sistema = {'No OS': 0, 'Windows 10': 1, 'Linux': 2, 'Mac OS X': 3, 'Android': 4, 'Chrome OS': 5, 'macOS': 6, 'Windows 7': 7, 'Windows 10 S':8}
train["OpSys"] = train["OpSys"].replace(sistema)

In [150]:
#En la columna "Weight", eliminar kg y convertirlo a float.
train["Weight"] = train["Weight"].str.replace("kg", "")
train["Weight"] = train["Weight"].astype(float)

In [151]:
train_1st = train[["laptop_ID", "Inches", "OpSys", "Weight", "Price_euros"]]
train_1st.head()

laptop_ID  Inches  OpSys  Weight  Price_euros
0       1104    15.6      1    2.40        387.0
1        114    13.3      1    1.23       1379.0
2        172    17.3      1    3.00        854.0
3        918    12.5      1    1.26       1483.0
4        447    17.3      1    2.80        519.0

-----------------------------------------------------------------------------------------------------------------

## Pasos que si o si debéis realizar para poder participar en la competición:

### 1. Definir X e y

In [152]:
X = train_1st.drop(['Price_euros'], axis=1)
y = train_1st['Price_euros'].copy()
X.shape

(912, 4)

In [153]:
y.shape

(912,)

### 2. Dividir X_train, X_test, y_train, y_test

In [154]:
from sklearn.model_selection import train_test_split

In [155]:
X_train, X_validation, y_train, y_validation= train_test_split(X, y, test_size = 0.20, random_state = 42)

In [156]:
X_train

laptop_ID  Inches  OpSys  Weight
25          26    15.6      1    2.30
84         776    15.6      1    2.72
10        1263    15.6      1    2.50
342        182    15.6      1    1.90
890        321    13.3      1    1.29
..         ...     ...    ...     ...
106        394    15.6      1    2.00
270        441    15.6      1    2.50
860        955    17.3      1    2.80
435        210    15.6      1    2.30
102        673    15.6      1    2.10

[729 rows x 4 columns]

### 3. Asignar el modelo (vacío) a una variable


In [157]:
from sklearn.linear_model import LinearRegression

laptop_model = LinearRegression()

### 4. Sacar métricas, valorar el modelo 

Recuerda que en la competición se va a evaluar con la métrica de MAE.

In [158]:
laptop_model.fit(X_train, y_train)
#OJO!! si ejecutamos esta celda más de una vez, hacemos overfitting

LinearRegression()

In [159]:
laptop_model.coef_

array([ 3.00893906e-02, -1.37587165e+02,  5.68403600e+01,  4.51417958e+02])

In [160]:
laptop_model.intercept_

2157.8911837690403

In [161]:
predictions = laptop_model.predict(X_validation)
predictions

array([ 990.34453872,  851.8608682 , 1062.33378088, 1073.522147  ,
       1090.94390414, 1425.72999607,  912.63831235, 1340.76322665,
       1063.71789284,  991.55391125,  867.43335991, 1106.95916988,
       1218.48532489, 1128.58913415,  938.48674698, 1200.67295203,
        804.23792976, 1116.83258602, 1189.98839558, 1193.03024682,
       1091.46031094, 1050.13986773,  976.83440235, 1115.05810311,
       1055.79872496, 1059.68723612,  957.15479887, 1783.27369351,
       1063.05592625, 1063.08189947, 1005.21834955,  886.19630595,
       1202.98080353, 1555.12593183, 1059.58804252, 1021.46467852,
       1041.32988508, 1227.70145315,  911.58374783, 1495.09765506,
       1094.4685561 , 1287.82982121,  925.21876159, 1842.70949184,
       1280.66314928,  948.51268201, 1042.61285331, 1041.29358691,
       1205.55232047, 1000.42756854, 1119.28688649,  922.93982482,
        834.48691309, 1387.41000233, 1362.70986022, 1350.43338887,
       1054.62975483,  777.42817662,  810.82981929, 1096.57293

In [162]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error ,mean_squared_error
import numpy as np

print("MAE: ", mean_absolute_error(y_validation, predictions))
print("MAPE: ", mean_absolute_percentage_error(y_validation, predictions))
print("MSE: ", mean_squared_error(y_validation, predictions))
print("RMSE: ", np.sqrt(mean_squared_error(y_validation, predictions)))#en cuanto me equivoco

MAE:  484.62807694528806
MAPE:  0.5992856484597536
MSE:  452019.57350678666
RMSE:  672.3240093190088


-----------------------------------------------------------------

## Una vez listo el modelo, toca predecir con el dataset de predicción 

Definición de **modelo que está listo**. 

Tras hacer suficientes pruebas, analizar los datos, hacer feature engineering, probar diferentes modelos con diferentes parámetros, es con este con el que observo mejores métricas y menos overfitting. ¡Cuidado con el overfitting aquí! Si vuestro modelo aprende muy bien de estos datos pero hay overfitting cuando le pasemos los datos desconocidos de `test.csv` nos arriesgamos a que digamos, no salga lo esperado.

### 1. Entrena dicho modelo con TODOS tus datos de train, esto es con `train.csv` al completo.


**CON LAS TRANSFORMACIONES QUE LE HAYAS REALIZADO A `X` INCLUÍDAS.**


Véase:
- Estandarización/Normalización
- Eliminación de Outliers
- Eliminación de columnas
- Creación de columnas nuevas
- Gestión de valores nulos
- Y un largo etcétera de técnicas que como Data Scientist hayas considerado las mejores para tu dataset.

### 2. Carga los datos de `test.csv` para predecir.

In [163]:
X_pred = pd.read_csv("data/test.csv")
X_pred.head()

laptop_ID   Company          Product            TypeName  Inches  \
0        750   Toshiba  Tecra X40-D-10G            Notebook    14.0   
1        726  Mediacom    Smartbook 142            Notebook    14.0   
2        633  Mediacom    SmartBook 140            Notebook    14.0   
3        363      Dell    Inspiron 7577              Gaming    15.6   
4        319      Asus    VivoBook Flip  2 in 1 Convertible    11.6   

                            ScreenResolution  \
0  IPS Panel Full HD / Touchscreen 1920x1080   
1                IPS Panel Full HD 1920x1200   
2                          Full HD 1920x1080   
3                          Full HD 1920x1080   
4                       Touchscreen 1366x768   

                                    Cpu  Ram              Memory  \
0            Intel Core i5 7200U 2.5GHz  8GB           256GB SSD   
1              Intel Atom Z8350 1.92GHz  4GB            32GB HDD   
2           Intel Atom x5-Z8350 1.44GHz  2GB  32GB Flash Storage   
3           Intel Core i5 7300HQ 2.5GHz  8GB             1TB HDD   
4  Intel Celeron Dual Core N3350 1.1GHz  2GB  32GB Flash Storage   

                       Gpu       OpSys  Weight  
0    Intel HD Graphics 620  Windows 10  1.25kg  
1    Intel HD Graphics 400  Windows 10   1.4kg  
2        Intel HD Graphics  Windows 10   1.4kg  
3  Nvidia GeForce GTX 1050  Windows 10  2.65kg  
4    Intel HD Graphics 500  Windows 10   1.1kg

In [164]:
test_1st = X_pred[["laptop_ID", "Inches", "OpSys", "Weight"]]
test_1st.head()

laptop_ID  Inches       OpSys  Weight
0        750    14.0  Windows 10  1.25kg
1        726    14.0  Windows 10   1.4kg
2        633    14.0  Windows 10   1.4kg
3        363    15.6  Windows 10  2.65kg
4        319    11.6  Windows 10   1.1kg

In [165]:
#En la columna "OpSys", convertimos los sistemas en números. Creamos diccionario
sistema = {'No OS': 0, 'Windows 10': 1, 'Linux': 2, 'Mac OS X': 3, 'Android': 4, 'Chrome OS': 5, 'macOS': 6, 'Windows 7': 7, 'Windows 10 S':8}
test_1st["OpSys"] = test_1st["OpSys"].replace(sistema)
#En la columna "Weight", eliminar kg y convertirlo a float.
test_1st["Weight"] = test_1st["Weight"].str.replace("kg", "")
test_1st["Weight"] = test_1st["Weight"].astype(float)

C:\Users\lydia\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\lydia\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\lydia\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from

In [166]:
test_1st.head()

laptop_ID  Inches  OpSys  Weight
0        750    14.0      1    1.25
1        726    14.0      1    1.40
2        633    14.0      1    1.40
3        363    15.6      1    2.65
4        319    11.6      1    1.10

**¿Por qué da error?** 

In [167]:
predictions_submit = laptop_model.predict(test_1st)
predictions_submit

array([ 875.35072462,  942.34127296,  939.54295964, 1275.55180787,
       1124.87869951, 1061.91252941,  740.95032211, 1538.18509513,
       1162.60705017, 1227.03614533,  851.25908039, 1031.00235048,
       1122.91143405, 1067.90031813,  932.29516535,  921.84874985,
        934.55843755, 1188.4848032 , 1076.95722469, 1033.56682231,
       1430.12243103,  999.37961646, 1140.48286714,  967.40948414,
        877.0456881 ,  838.57532137, 1096.66500452, 1050.14889931,
       1068.77291046, 1220.05540672,  982.61310733,  986.64354368,
       1181.35274049, 1185.17409309, 1000.21385882,  873.43454937,
        993.71455046, 1243.81991454, 1181.65374054, 1019.99378231,
       1799.34142808, 1197.57863197, 1276.42851242, 1287.61709892,
       1017.55305775, 1414.34643605, 1177.1139914 , 1204.55448341,
       1053.08605383, 1122.84405511, 1485.10720639, 1149.50810151,
       1087.64204233, 1293.16392052, 1006.06511933, 1016.04396224,
       1106.15785228, 1439.63129451, 1020.26304483, 1083.07193

IMPORTANTE: APLICAR LO MISMO A ESTOS DATOS QUE HAYÁIS APLICADO A LOS DATOS DE ENTRENAMIENTO

- SI EL ARRAY CON EL QUE HICISTEIS `.fit()` ERA DE 4 COLUMNAS, PARA `.predict()` DEBEN SER LAS MISMAS
- SI AL ARRAY CON EL QUE HICISTEIS `.fit()` LO NORMALIZASTEIS, PARA `.predict()` DEBÉIS NORMALIZARLO
- TODO IGUAL SALVO BORRAR FILAS, EL NÚMERO DE ROWS SE DEBE MANTENER EN ESTE SET, PUES LA PREDICCIÓN DEBE TENER 391 FILAS, SI O SI

**Entonces, si al cargar los datos de train usé `index_col=0` para que utilizara la primera columna del conjunto de datos como índice, ¿tendré que hacerlo también para el conjunto `test.csv`?**

In [168]:
# ¿Qué opináis?
# Sí

![](https://www.tierraljelechu.com/web/img/wiki_up/1.996-SorpresaDto.-1-Red.jpg)

### 3. AHORA puedo hacer la predicción que será lo que subirás a Kaggle. 

**¿Qué es lo que subirás a Kaggle?**

In [170]:
predictions_submit = laptop_model.predict(test_1st)
predictions_submit

array([ 875.35072462,  942.34127296,  939.54295964, 1275.55180787,
       1124.87869951, 1061.91252941,  740.95032211, 1538.18509513,
       1162.60705017, 1227.03614533,  851.25908039, 1031.00235048,
       1122.91143405, 1067.90031813,  932.29516535,  921.84874985,
        934.55843755, 1188.4848032 , 1076.95722469, 1033.56682231,
       1430.12243103,  999.37961646, 1140.48286714,  967.40948414,
        877.0456881 ,  838.57532137, 1096.66500452, 1050.14889931,
       1068.77291046, 1220.05540672,  982.61310733,  986.64354368,
       1181.35274049, 1185.17409309, 1000.21385882,  873.43454937,
        993.71455046, 1243.81991454, 1181.65374054, 1019.99378231,
       1799.34142808, 1197.57863197, 1276.42851242, 1287.61709892,
       1017.55305775, 1414.34643605, 1177.1139914 , 1204.55448341,
       1053.08605383, 1122.84405511, 1485.10720639, 1149.50810151,
       1087.64204233, 1293.16392052, 1006.06511933, 1016.04396224,
       1106.15785228, 1439.63129451, 1020.26304483, 1083.07193

**¡PERO! Para subir a Kaggle la predicción, ésta tendrá que tener una forma específica y no valdrá otra.**

En este caso, la **MISMA** forma que `sample_submission.csv`. 

In [176]:
test_1st.head()

laptop_ID  Inches  OpSys  Weight
0        750    14.0      1    1.25
1        726    14.0      1    1.40
2        633    14.0      1    1.40
3        363    15.6      1    2.65
4        319    11.6      1    1.10

In [171]:
sample = pd.read_csv("data/sample_submission.csv")

In [172]:
sample.head()

laptop_ID  Price_euros
0        750          500
1        726          500
2        633          500
3        363          650
4        319          650

In [173]:
sample.shape

(391, 2)

### 4. Mete tus predicciones en un dataframe. 

En este caso, la **MISMA** forma que `sample_submission.csv`. 

In [174]:
submission = pd.DataFrame({"laptop_ID": sample["laptop_ID"], "Price_euros": predictions_submit})
# cuando haya eliminado columnas, el laptop ID será del csv que tenga los datos limpios ( que coincida laptop id con los datos que nos hemos quedado)

In [175]:
submission.head()

laptop_ID  Price_euros
0        750   875.350725
1        726   942.341273
2        633   939.542960
3        363  1275.551808
4        319  1124.878700

In [177]:
submission.shape

(391, 2)

### 5. Pásale el CHEQUEATOR para comprobar que efectivamente está listo para subir a Kaggle.

In [178]:
def chequeator(df_to_submit):
    """
    Esta función se asegura de que tu submission tenga la forma requerida por Kaggle.
    
    Si es así, se guardará el dataframe en un `csv` y estará listo para subir a Kaggle.
    
    Si no, LEE EL MENSAJE Y HAZLE CASO.
    
    Si aún no:
    - apaga tu ordenador, 
    - date una vuelta, 
    - enciendelo otra vez, 
    - abre este notebook y 
    - leelo todo de nuevo. 
    Todos nos merecemos una segunda oportunidad. También tú.
    """
    if df_to_submit.shape == sample.shape:
        if df_to_submit.columns.all() == sample.columns.all():
            if df_to_submit.laptop_ID.all() == sample.laptop_ID.all():
                print("You're ready to submit!")
                submission.to_csv("submission1.csv", index = False) #muy importante el index = False
                urllib.request.urlretrieve("https://i.kym-cdn.com/photos/images/facebook/000/747/556/27a.jpg", "gfg.png")     
                img = Image.open("gfg.png")
                img.show()   
            else:
                print("Check the ids and try again")
        else:
            print("Check the names of the columns and try again")
    else:
        print("Check the number of rows and/or columns and try again")
        print("\nMensaje secreto de Clara: No me puedo creer que después de todo este notebook hayas hecho algún cambio en las filas de `diamonds_test.csv`. Lloro.")


In [179]:
chequeator(submission)

You're ready to submit!
